import {
  Camera, Smartphone, Settings, DoorOpen, Lock, Cog, Home, Mic, Lightbulb, Sun, Radar, Bell, KeyRound, Plug, Droplets, Tv, Wrench, MessageSquare, Sparkles,
  type LucideIcon,
} from "lucide-react";

export interface Service {
  slug: string;
  title: string;
  icon: LucideIcon;
  short: string;
  long: string;
  keywords: string[];
}

export const SERVICES: Service[] = [
  { slug: "instalacao-cameras", title: "Instalação de Câmeras", icon: Camera,
    short: "Sistemas profissionais de monitoramento residencial e empresarial.",
    long: "Projetamos e instalamos sistemas de câmeras Intelbras, Hikvision e Ezviz com gravação local e em nuvem, visão noturna, detecção inteligente e visualização remota pelo aplicativo.",
    keywords: ["instalação de câmeras florianópolis", "câmeras rio vermelho", "intelbras"] },
  { slug: "monitoramento-aplicativo", title: "Monitoramento por Aplicativo", icon: Smartphone,
    short: "Acompanhe sua casa em tempo real, de qualquer lugar.",
    long: "Configuração completa de aplicativos como iSIC, Mibo, EZVIZ e Hik-Connect, com notificações inteligentes e múltiplos usuários.",
    keywords: ["monitoramento câmeras app", "câmera celular"] },
  { slug: "configuracao-completa", title: "Configuração Completa", icon: Settings,
    short: "Você compra, a gente configura e entrega funcionando.",
    long: "Cuidamos de toda a parametrização: rede, gravação, qualidade, máscaras de privacidade, integração com Alexa e Google Home.",
    keywords: ["configuração câmeras"] },
  { slug: "video-porteiro", title: "Vídeo Porteiro", icon: Tv,
    short: "Veja e fale com quem chega — mesmo fora de casa.",
    long: "Vídeo porteiros IP com atendimento pelo celular, gravação automática e integração com fechaduras eletrônicas.",
    keywords: ["video porteiro florianópolis"] },
  { slug: "fechaduras-eletronicas", title: "Fechaduras Eletrônicas", icon: Lock,
    short: "Acesso por digital, senha, cartão ou aplicativo.",
    long: "Instalação de fechaduras digitais Intelbras, Papaiz e Yale, com integração à automação residencial.",
    keywords: ["fechadura eletrônica florianópolis"] },
  { slug: "portoes-eletronicos", title: "Portões Eletrônicos", icon: DoorOpen,
    short: "Automatização e manutenção de portões basculantes e deslizantes.",
    long: "Motores PPA, Garen e Rossi com central nova, controle remoto, integração ao aplicativo e botoeira.",
    keywords: ["portão eletrônico florianópolis"] },
  { slug: "automacao-residencial", title: "Automação Residencial", icon: Home,
    short: "Sua casa respondendo por comando de voz ou toque.",
    long: "Cenários personalizados de iluminação, climatização, áudio e segurança via Alexa, Google Home e Apple Home.",
    keywords: ["automação residencial florianópolis", "automação alexa florianópolis"] },
  { slug: "alexa-google-home", title: "Alexa & Google Home", icon: Mic,
    short: "Configuração e integração de assistentes de voz.",
    long: "Pareamento de dispositivos, rotinas personalizadas e treinamento da família para usar o sistema com confiança.",
    keywords: ["alexa florianópolis"] },
  { slug: "interruptores-inteligentes", title: "Interruptores Inteligentes", icon: Plug,
    short: "Controle qualquer luz pelo celular ou voz.",
    long: "Instalação de interruptores Wi-Fi e ZigBee sem quebrar parede, mantendo o acabamento da sua casa.",
    keywords: ["interruptor inteligente"] },
  { slug: "iluminacao-inteligente", title: "Iluminação Inteligente", icon: Lightbulb,
    short: "Cenas, dimerização e cores sob comando.",
    long: "Projetos com Philips Hue, Positivo Casa Inteligente e fitas LED endereçáveis.",
    keywords: ["iluminação inteligente"] },
  { slug: "sensores", title: "Sensores", icon: Radar,
    short: "Presença, abertura, fumaça e gás — você no controle.",
    long: "Integração com aplicativo, alarmes e automações de iluminação para máxima segurança.",
    keywords: ["sensores residenciais"] },
  { slug: "alarmes", title: "Alarmes", icon: Bell,
    short: "Centrais Intelbras com aviso em tempo real no celular.",
    long: "Sirenes, sensores e centrais monitoradas via aplicativo AMT Mobile e iSIC.",
    keywords: ["alarme residencial"] },
  { slug: "controle-de-acesso", title: "Controle de Acesso", icon: KeyRound,
    short: "Catracas, leitores biométricos e cartões para empresas e condomínios.",
    long: "Soluções para pequenos comércios, escritórios e condomínios.",
    keywords: ["controle de acesso"] },
  { slug: "servicos-eletricos", title: "Pequenos Serviços Elétricos", icon: Wrench,
    short: "Apoio elétrico necessário para sua automação.",
    long: "Troca de tomadas, pontos novos, organização de quadros e infraestrutura para os dispositivos.",
    keywords: ["eletricista florianópolis"] },
  { slug: "servicos-hidraulicos", title: "Pequenos Serviços Hidráulicos", icon: Droplets,
    short: "Pequenos reparos e instalações pontuais.",
    long: "Apoio em adequação de pontos hidráulicos para dispositivos inteligentes.",
    keywords: ["hidráulica"] },
  { slug: "suportes-tv", title: "Instalação de Suportes de TV", icon: Tv,
    short: "Fixação segura e organização dos cabos.",
    long: "Instalação de suportes fixos, articulados e ocultação de fiação.",
    keywords: ["instalação suporte tv"] },
  { slug: "montagem-equipamentos", title: "Montagem de Equipamentos", icon: Cog,
    short: "Montamos, configuramos e entregamos pronto para uso.",
    long: "Hubs, roteadores mesh, repetidores, NVRs e gravadores.",
    keywords: ["montagem equipamentos"] },
  { slug: "consultoria-residencial", title: "Consultoria Residencial", icon: MessageSquare,
    short: "Definimos o melhor sistema para sua casa.",
    long: "Visita técnica, levantamento de necessidades e proposta detalhada — sem compromisso.",
    keywords: ["consultoria automação"] },
  { slug: "configuracao-dispositivos", title: "Configuração de Dispositivos", icon: Sparkles,
    short: "Você compra. Nós configuramos.",
    long: "Configuração isolada para quem já comprou os equipamentos e precisa apenas de instalação.",
    keywords: ["configuração smart"] },
  { slug: "automacao-cortinas", title: "Cortinas Automatizadas", icon: Sun,
    short: "Abra e feche cortinas por horário, voz ou cena.",
    long: "Motorização discreta para cortinas e persianas com integração ao Alexa e Google Home.",
    keywords: ["cortinas automatizadas"] },
];

export const PRODUCT_CATEGORIES = [
  { slug: "cameras", title: "Câmeras", desc: "Bullet, dome, Wi-Fi e PTZ para todos os ambientes." },
  { slug: "fechaduras", title: "Fechaduras", desc: "Digitais, biométricas e integradas à automação." },
  { slug: "portoes", title: "Portões", desc: "Motores, controles e centrais para portões." },
  { slug: "sensores", title: "Sensores", desc: "Presença, abertura, fumaça e vazamento." },
  { slug: "automacao", title: "Automação", desc: "Interruptores, dimmers, hubs e fitas LED." },
  { slug: "alexa", title: "Alexa", desc: "Echo, Echo Dot e dispositivos compatíveis." },
  { slug: "google-home", title: "Google Home", desc: "Nest Hub, Mini e ecossistema Google." },
];

// ===== Contact info =====
export const CONTACT = {
  phoneDisplay: "(48) 98426-0224",
  phoneIntl: "+55 48 98426-0224",
  phoneHref: "tel:+5548984260224",
  whatsappNumber: "5548984260224",
  whatsappMessage: "Olá! Gostaria de solicitar um orçamento.",
  email: "contato@sameirosolucoes.com.br",
  mailHref: "mailto:contato@sameirosolucoes.com.br",
  addressLine: "Rodovia José Carlos Daux, 1000 — Florianópolis/SC",
  addressStreet: "Rodovia José Carlos Daux, 1000",
  city: "Florianópolis",
  region: "SC",
  postal: "88050-001",
  country: "BR",
  mapsUrl: "https://www.google.com/maps/search/?api=1&query=Rodovia+Jos%C3%A9+Carlos+Daux+1000+Florian%C3%B3polis",
} as const;

export const WHATSAPP_URL = `https://wa.me/${CONTACT.whatsappNumber}?text=${encodeURIComponent(CONTACT.whatsappMessage)}`;
