/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AutomacaoRouteImport } from './routes/automacao'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicosSlugRouteImport } from './routes/servicos.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomacaoRoute = AutomacaoRouteImport.update({
  id: '/automacao',
  path: '/automacao',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosSlugRoute = ServicosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/automacao': typeof AutomacaoRoute
  '/blog': typeof BlogRoute
  '/contato': typeof ContatoRoute
  '/produtos': typeof ProdutosRoute
  '/projetos': typeof ProjetosRoute
  '/quem-somos': typeof QuemSomosRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/servicos/$slug': typeof ServicosSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/automacao': typeof AutomacaoRoute
  '/blog': typeof BlogRoute
  '/contato': typeof ContatoRoute
  '/produtos': typeof ProdutosRoute
  '/projetos': typeof ProjetosRoute
  '/quem-somos': typeof QuemSomosRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/servicos/$slug': typeof ServicosSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/automacao': typeof AutomacaoRoute
  '/blog': typeof BlogRoute
  '/contato': typeof ContatoRoute
  '/produtos': typeof ProdutosRoute
  '/projetos': typeof ProjetosRoute
  '/quem-somos': typeof QuemSomosRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/servicos/$slug': typeof ServicosSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/automacao'
    | '/blog'
    | '/contato'
    | '/produtos'
    | '/projetos'
    | '/quem-somos'
    | '/servicos'
    | '/sitemap.xml'
    | '/servicos/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/automacao'
    | '/blog'
    | '/contato'
    | '/produtos'
    | '/projetos'
    | '/quem-somos'
    | '/servicos'
    | '/sitemap.xml'
    | '/servicos/$slug'
  id:
    | '__root__'
    | '/'
    | '/automacao'
    | '/blog'
    | '/contato'
    | '/produtos'
    | '/projetos'
    | '/quem-somos'
    | '/servicos'
    | '/sitemap.xml'
    | '/servicos/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutomacaoRoute: typeof AutomacaoRoute
  BlogRoute: typeof BlogRoute
  ContatoRoute: typeof ContatoRoute
  ProdutosRoute: typeof ProdutosRoute
  ProjetosRoute: typeof ProjetosRoute
  QuemSomosRoute: typeof QuemSomosRoute
  ServicosRoute: typeof ServicosRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automacao': {
      id: '/automacao'
      path: '/automacao'
      fullPath: '/automacao'
      preLoaderRoute: typeof AutomacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/$slug': {
      id: '/servicos/$slug'
      path: '/$slug'
      fullPath: '/servicos/$slug'
      preLoaderRoute: typeof ServicosSlugRouteImport
      parentRoute: typeof ServicosRoute
    }
  }
}

interface ServicosRouteChildren {
  ServicosSlugRoute: typeof ServicosSlugRoute
}

const ServicosRouteChildren: ServicosRouteChildren = {
  ServicosSlugRoute: ServicosSlugRoute,
}

const ServicosRouteWithChildren = ServicosRoute._addFileChildren(
  ServicosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutomacaoRoute: AutomacaoRoute,
  BlogRoute: BlogRoute,
  ContatoRoute: ContatoRoute,
  ProdutosRoute: ProdutosRoute,
  ProjetosRoute: ProjetosRoute,
  QuemSomosRoute: QuemSomosRoute,
  ServicosRoute: ServicosRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
